package duke.command;

import duke.DukeException;
import duke.task.TaskList;
import duke.ui.Ui;

/**
 * Represents a command that can be executed by the Duke application.
 * Concrete subclasses of Command define specific actions to be performed.
 */
public abstract class Command {
    protected String input;

    /**
     * Constructs a Command object with the specified input.
     *
     * @param input The input string associated with the command.
     */
    public Command(String input) {
        this.input = input;
    }

    /**
     * Executes the command and generates a response.
     *
     * @param ui      The UI instance to interact with the user.
     * @param tasks   The TaskList containing tasks to be manipulated.
     * @param storage The Storage instance to read from or write to files.
     * @return The response message generated by executing the command.
     * @throws DukeException If an error occurs during command execution.
     */
    public abstract String executeAndReply(Ui ui, TaskList tasks, Storage storage) throws DukeException;

    /**
     * Checks if the command indicates a termination request. This method is
     * overridden in ByeCommand class to return true.
     *
     * @return True if it is a bye command, false otherwise.
     */
    public boolean isBye() {
        return false;
    }
}
