package duke;

import javafx.application.Application;
import javafx.application.Platform;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.ScrollPane;
import javafx.scene.control.TextField;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.Region;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

/**
 * This class represents the main driver of the application.
 * It initializes the task list, storage, and user interface, and starts the user interface.
 */
public class Bird {
    private CommandHandler commandHandler;

    /**
     * Constructs a new Bird ChatBot.
     * Initializes the task list, storage, and user interface, and starts the user interface.
     */
    public Bird() {
        TaskList.create();
        Storage.init();
        commandHandler = new CommandHandler(this);
    }

    /**
     * Gets the response for a given user input by executing the corresponding command.
     *
     * @param input The user's input.
     * @return The response generated by executing the command.
     */
    public String getResponse(String input) {
        String response;
        try {
            response = commandHandler.executeCommand(input);
        } catch (DukeException e) {
            response = e.getMessage();
        }
        return response;
    }

    /**
     * Generates a greeting message and displays it in the GUI.
     */
    public String greet() {
        String greeting = " /\\_/\\ \n" +
                "((@v@)) \n" +
                "():::() \n" +
                " VV-VV \n" +
                "What can I do for you?";

        return greeting;
    }



}

