package duke;

/**
 * This class represents the main driver of the application.
 * It initializes the task list, storage, and user interface, and starts the user interface.
 */
public class Bird {
    private CommandHandler commandHandler;

    /**
     * Constructs a new Bird ChatBot.
     * Initializes the task list, storage, and user interface, and starts the user interface.
     */
    public Bird() {
        TaskList.create();
        Storage.init();
        commandHandler = new CommandHandler();
    }

    /**
     * Gets the response for a given user input by executing the corresponding command.
     *
     * @param input The user's input.
     * @return The response generated by executing the command.
     */
    public String getResponse(String input) {
        String response;
        try {
            response = commandHandler.executeCommand(input);
        } catch (DukeException e) {
            response = e.getMessage();
        }
        assert response != null: "Response returned by Duke should not be null!";
        return response;
    }

    /**
     * Generates a greeting message
     */
    public String greet() {
        return "Hello I'm Bird! \n" +
                "What can I do for you?";
    }
}

