name: Java CI

on: [push, pull_request] # Triggers the workflow on push and pull_request events

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest] # Defines a matrix of different platforms
    runs-on: ${{ matrix.platform }} # Specifies the platform dynamically determined by the matrix

    steps:
      - name: Set up repository  # Checks out the source code of the repository
        uses: actions/checkout@master

      - name: Set up repository
        uses: actions/checkout@master
        with:
          ref: master #This ensures that the codebase is checked out from the master branch,
                      #regardless of the default branch setting in the repository.

      - name: Merge to master # Checks out the specific commit associated with the event
        run: git checkout --progress --force ${{ github.sha }}

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk+fx

      - name: Build and check with Gradle
        run: ./gradlew check

#      - name: Perform IO redirection test (*NIX)
#        if: runner.os == 'Linux'
#        working-directory:  ${{ github.workspace }}/text-ui-test
#        run: ./runtest.sh
#
#      - name: Perform IO redirection test (MacOS)
#        if: always() && runner.os == 'macOS'
#        working-directory:  ${{ github.workspace }}/text-ui-test
#        run: ./runtest.sh
#
#      - name: Perform IO redirection test (Windows)
#        if: always() && runner.os == 'Windows'
#        working-directory:  ${{ github.workspace }}/text-ui-test
#        shell: cmd
#        run: runtest.bat