package youdon;

/**
 * The main class for YoudonBot.
 */
public class Youdon {

    private final Parser parser;

    /**
     * Constructs a new instance of the Youdon class.
     * Initializes the user interface, storage, task list, and parser.
     */
    public Youdon() {
        // initialise ui, storage (filepath = "./data/save.txt") and tasklist
        Ui ui = new Ui();
        Storage storage = new Storage("./data/save.txt");
        TaskList tasks = new TaskList(storage.loadData());
        this.parser = new Parser(ui, tasks, storage);
    }

    /**
     * The main method of the application.
     * This method is empty as YoudonBot has switched from CLI to GUI.
     *
     * @param args The command-line arguments passed to the application.
     */
    public static void main(String[] args) {

    }

    /**
     * Get YoudonBot's response based on the input.
     *
     * @param input The user input to process.
     * @return The response generated by the chatbot.
     */
    protected String getResponse(String input) {
        return parser.parse(input);
    }

}
